### ISSUE TITLE
CRDs to cover all major spark configuration properties.

### ISSUE THREAD

**Issue by adwk67** [stackabletech/spark-k8s-operator#1]
### Summary 
As a user of spark-on-k8s I want to be able to use CRDs that cover all major spark configuration properties.

### Detail
The initial spike (in branch `spark-submit-wrapper`) parses the CRD to build a spark-submit command, which is then executed as a job issued from the controller. This job is executed by spark (by passing it through the entrypoint.sh script in the spark docker image used for spawning the driver and executors), by first creating the driver (living in its own pod), which then creates temporary executors. Once the job is completed, the driver and the job that created it, are still visible:

![image](https://user-images.githubusercontent.com/1712947/158588206-96278223-300b-4234-acc1-883ed7d485c0.png)

### Implementation
This issue covers the following:

- investigate alternatives to the above, specifically if it is better to do away with the interim job and instead create the driver directly from the controller, documenting how this is done (or why it is not done)
- implement the configuration properties listed in the comment [below](https://github.com/stackabletech/spark-k8s-operator/issues/1#issuecomment-1069060379)

### Update 2022-05-16
Remaining options are marked in this [comment](https://github.com/stackabletech/spark-k8s-operator/issues/1#issuecomment-1083053646) with `TODO`.

**Comment by fhennig** [comment]
Uh oh, what are the major ones? :laughing:

**Comment by adwk67** [comment]
I would suggest we start with the ones that `spark-submit -h` minus things like kerberos keytab, maven repositories e.g.

  --master
  --deploy-mode
  --class
  --name
  --jars
  --packages
  --exclude-packages 
  --py-files
  --files
  --archives 
  --conf, -c PROP=VALUE
  --properties-file
  --driver-memory
  --driver-java-options
  --driver-library-path
  --driver-class-path
  --executor-memory
  --driver-cores
  --total-executor-cores
  --executor-cores
  --num-executors

**Comment by sbernauer** [comment]
I would suggest including the following informations in CRD. They don't need to be implemented for the first version, just for the records and to keep that in mind when designing the CRD.
* Wether it is a single time Job (e.g. ETL job; backed by a k8s Job) or a Deployment (e.g. streaming job; backed by a k8s Cronjob)
* Allow specifying the retry policy of the Job. Some jobs can be retried, some not as they otherwise compromise data.

I'm also happy to create issues out of this if you prefer ;)

**Comment by soenkeliebau** [comment]
Just one comment that occurred while reading: do we want to make '--master MASTER_URL' configurable? Shouldn't that be an implementation detail because we are the ones who know best where the master is?

**Comment by adwk67** [comment]
Yes, you're right. In fact in the spike I've ignored `--master` and read the api server host/port directly from the environment variables in the pod.

**Comment by adwk67** [comment]
Update:


```
  --master MASTER_URL         done: read from env vars
  --deploy-mode DEPLOY_MODE   done: leave as cluster mode for the time being
  --class CLASS_NAME          done
  --name NAME                 done
  --jars JARS                 done: made available via PV/PVCs and spark.{driver|executor}.extraClassPath
  --packages                  done (for python packages)
  --conf, -c PROP=VALUE       done
  --driver-memory MEM         done
  --executor-memory MEM       done
  --driver-cores NUM          done
  --total-executor-cores NUM  done
  --executor-cores NUM        done
  --num-executors NUM         done
  --repositories              done

  --driver-java-options       TODO
  --driver-library-path       TODO
  --driver-class-path         TODO
  --properties-file FILE      TODO
  --exclude-packages          TODO
  --py-files PY_FILES         TODO
  --files FILES               TODO
  --archives ARCHIVES         TODO
```

**Comment by razvan** [comment]
I propose to close this issue and implement the remaining args _if necessary_ on a case by case basis.
