### ISSUE TITLE
Research: spark-k8s job orchestration

### ISSUE THREAD

**Issue by adwk67** [stackabletech/spark-k8s-operator#121]
As a user I want to have a plan/outline/overview of how to orchestrate spark jobs running in k8s. This will involve looking at Airflow (i.e. airflow/spark-k8s interplay) and [Yunikorn](https://yunikorn.apache.org/) or [Furiko](https://furiko.io/blog/introducing-furiko/).

This is a research ticket: as a result we will able to

- understand pros/cons
- be able to estimate implementation effort
- define specific implementation ticket(s)

**Comment by adwk67** [comment]
See https://github.com/stackabletech/airflow-operator/pull/155

**Comment by adwk67** [comment]
##### Yunikorn

- a resource scheduler rather than a job scheduler
- very non-invasive: install the Yunikorn components and you are good to go
- it overrides the default k8s resource scheduler whenever the admission-controller is installed
- it comes with a UI that provides an overview for running, queued and completed jobs
- default config files can be found here: https://github.com/apache/yunikorn-core/tree/master/config

##### Furiko

- https://github.com/furiko-io/furiko is a job scheduler
- is in its infancy (< 5 committers, 3 releases, first commit 2022-03-24)
- it currently only supports running a task for a Pod https://furiko.io/docs/execution/job/task-executor#task-executor-list though more are on the roadmap https://furiko.io/docs/contributing/roadmap

Since neither of the above are viable for running & scheduling spark jobs, we have....

##### Airflow
- see stackabletech/airflow-operator#155 for documentation on how to call/apply custom resources from airflow running in-cluster

**Comment by lfrancke** [comment]
Thank you!
Can you elaborate a bit on the differences between job and resource scheduler?
Can I implement "queue" like things using Yunikorn? To separate workloads from e.g. different departments? (they get 40% of the cluster, we get 20% and the rest is for evreyone else)

**Comment by lfrancke** [comment]
Okay! In this case the customer was referring to the resource scheduling part of things.
So Yunikorn would be a solution for us. Thank you!
