### ISSUE TITLE
Implement ADR 22 (Spark history server)

### ISSUE THREAD

**Issue by razvan** [stackabletech/spark-k8s-operator#124]
## Description

Add the possibility to provision Spark history servers as described in [ADR022](https://docs.stackable.tech/home/stable/contributor/adr/ADR022-spark-history-server.html).
See: #84 

## Acceptance criteria

- [ ]  Can set up history servers and spark applications can log to them.
- [ ] Can clean up history servers.
- [ ] Documentation is updated.
- [ ] Tests are added.

**Comment by lfrancke** [comment]
None of the boxes have been ticked and has this been added to the feature tracker?
