### ISSUE TITLE
OpenShift compatibility

### ISSUE THREAD

**Issue by razvan** [stackabletech/spark-k8s-operator#125]
## Description

Part of the epic: https://github.com/stackabletech/issues/issues/234

## Acceptance criteria

- [ ] Can run Spark applications on OpenShift.
- [ ] The kuttl tests run on OpenShift.
- [ ] **This isue changes the `values.yaml` file of the Helm chart. This file get's overwritten by the `operator-templating`. A solution for this has been found.**

**Comment by lfrancke** [comment]
None of the checkboxes have been ticked, could you update the ticket?
