### ISSUE TITLE
Support for Java 17

### ISSUE THREAD

**Issue by adwk67** [stackabletech/spark-k8s-operator#149]
Spark 3.3.0 supported java 8 and 11: the current version (3.3.0) supports 8/11/17. This issue covers adding support for Java 17 to the spark-k8s image.

This ticket will cover:

- adding java-base as an extra option in conf.py to give the possibility to compile the spark-k8s images against either 11 or 17.
- adding java version as a dimension for the kuttl tests

**Comment by razvan** [comment]
Can this be closed ? It looks done to me.
