### ISSUE TITLE
Support validation of custom S3 ca certificates

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/spark-k8s-operator#194]
Context https://github.com/stackabletech/spark-k8s-operator/pull/187#discussion_r1072142225

On-prem S3 often use a ca cert from an internal PKI. To be able to talk to on-prem S3 stores we need to implement using ca.crt of SecretClasses to validate S3 certificates.
This is already correctly implemented in Trino, some links are [here](https://github.com/stackabletech/trino-operator/blob/929c83f7e7c4143d32fff080aeeda484d8c87895/rust/operator-binary/src/controller.rs#L438-L440) and [here](https://github.com/stackabletech/trino-operator/blob/929c83f7e7c4143d32fff080aeeda484d8c87895/rust/operator-binary/src/command.rs#L120-L153).

IMHO this is a important feature as well as a bug as we don't respect what the user has entered into the S3Connection.

**Acceptance criteria:**
- [ ] Being able to add ca.cert to the java trust store (as a secret)
- [ ] Having tests in place
- [ ] New functionality is documented

**Comment by lfrancke** [comment]
None of the boxes have been ticked. Can you please make sure to update the ticket
