### ISSUE TITLE
Configure pod logging

### ISSUE THREAD

**Issue by adwk67** [stackabletech/spark-k8s-operator#24]
As a user of the spark-k8s-operator I want to "catch" logging outputs from short-lived pods and to define where log output can be found.

- shutdown hook for last-ditch logging? (dependent on Vector-logging issue?)
- change log4j properties to log out to a specified file (helps debugging etc.)

**Comment by maltesander** [comment]
Closing in favor of https://github.com/stackabletech/spark-k8s-operator/issues/218
