### ISSUE TITLE
submit spark jobs in client-mode

### ISSUE THREAD

**Issue by adwk67** [stackabletech/spark-k8s-operator#25]
As a user of the spark-k8s-operator I want to be able to submit spark jobs in client mode to save the creation of an interim pod.

- look up spark.driver.host + client mode: best way to do this? Alternative: maybe create a service that resolves to the driver pod.

**Comment by adwk67** [comment]
moving this issue back out of in-progress:

- it's not clear how much of an advantage this brings as operating in cluster mode means creating an additional pod, but that is TTL-ed out anyway
- instead of creating init containers for the driver/executors (for copying resources and installing python requirements), this would have to be done differently if our job pod is also where the driver is run from: initially we will just run one paradigm to keep things uncluttered
- it's not immediately clear if spark overwrites the name of the driver pod, which means we can't just pass it through as part of the `spark-submit` command

**Comment by razvan** [comment]
I propose to close this issue.
