### ISSUE TITLE
fix: reinstate setting for spark.executor.cores

### ISSUE THREAD

**Issue by adwk67** [stackabletech/spark-k8s-operator#300]
The setting for `spark.executor.cores` should be re-instated as is not enough to rely on `spark.kubernetes.executor.cores`.

From [here](https://blog.cloudera.com/how-to-tune-your-apache-spark-jobs-part-2/):

> The cores property controls the number of concurrent tasks an executor can run. --executor-cores 5 means that each executor can run a maximum of five tasks at the same time. 

If only `spark.kubernetes.executor.cores` is set, then the request in the pod definition is correct, but the executor application itself does not know how many concurrent tasks can be run.

**Comment by lfrancke** [comment]
Is this a breaking/CRD change?

**Comment by adwk67** [comment]
no, just an internal code change
