### ISSUE TITLE
Lots of optional properties shouldn't be optional

### ISSUE THREAD

**Issue by fhennig** [stackabletech/spark-k8s-operator#320]
I see that almost all SparkApplication properties are Optional, and at least some of them are actually required and cause an error if they are missing. For example the `main_application_file`.

Potential fix: make the required properties actually mandatory and not optional.

**Comment by lfrancke** [comment]
Is this a breaking change and is it a CRD change?

**Comment by adwk67** [comment]
Technically breaking, but not so in practice. From the changelog:

> Removed version field. Several attributes have been changed to mandatory. While this change is
  technically breaking, existing Spark jobs would not have worked before as these attributes were necessary
