### ISSUE TITLE
Support the use of java, python and (optionally) scala artifacts.

### ISSUE THREAD

**Issue by adwk67** [stackabletech/spark-k8s-operator#5]
As a user of spark-on-k8s I want to be able to start jobs that use java, python and (optionally) scala artifacts. Java and scala artifacts are both covered by JVM-integration, but python (and R, which is out of scope) jobs require different images.

The specific versions that should be supported are defined in issue #4.

**Comment by fhennig** [comment]
If we do want to use images for the executors (and not mount everything in a volume) we can specify the image we want to use with `spark.kubernetes.driver.container.image` and `spark.kubernetes.executor.container.image`. I think I'd just use different images based on the job type.
