### ISSUE TITLE
Make dependencies - spark and otherwise - available to spark pods externally via e.g. volumes, s3 etc.

### ISSUE THREAD

**Issue by adwk67** [stackabletech/spark-k8s-operator#6]
### Summary 
As a user of spark-on-k8s I want to make my dependencies - spark and otherwise - available to my pods externally via e.g. volumes, s3 etc.

### Goal/Motivation
Spark jobs can typically involve the use of a large number of artifacts (e.g. .jar files) that need to be available on the spark classpath. It is helpful to be able to make these available in a way that is not part of the spark-image:

- flexibility: artifacts/data etc. that are not tightly bound to the job image can be quickly and easily replaced, extended and refined
- efficiency: they only have to be defined in one place
- image size: in some scenarios it may also enable image size to be more manageable, although, in the case of spark libraries, these dependencies may well be copied to each executor image anyway

### Implementation

- Many of the possibilities **_may_** require us implementing a mutating admission webhook (see the list at the bottom for features that require this, according to the [google operator documentation](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md)
- a rudimentary implementation would involve e.g. copying these dependencies in the job image
  - this does not address the issue of flexibility
  - this would not require an extra component such as an admission webhook

### Goal/Definition of Done
The goal of this story is to: 

- use the bootstrap job covered by #9 to execute a simple custom job
- external dependencies = data *and* libraries
- investigate using external dependencies using at least of two of the following, documenting 
  - which are possible out-of-the-box
  - which require a mutation admission webhook
  - an estimate of effort/steps required to implement a mutation admission webhook
- approaches:
  - an init container
  - a volume mount

The story should include a clear decision/explanation of whether and how an admission webhook is required.
  
### Links
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#write-an-admission-webhook-server

N.B. a mutating admission webhook is [required](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md) for configuring the following:

- configMaps
- volumes
- pod affinity
- GPU resources
- host network
- tolerations
- security context
- init-containers
- DNS settings

**Comment by fhennig** [comment]
There seems to be support already for mounting a `PersistentVolume` into the pods. I think job dependencies could be mounted like that.

For s3, I'm not sure how that would be done.

**Comment by sbernauer** [comment]
Regarding the fiddling with the AdmissionWebHook to have a hook to modify Spark's k8s Manifest: You might be interested in a feature of Spark 3.2 to have a convenient programmatic hook
https://issues.apache.org/jira/browse/SPARK-33261 and https://github.com/apache/spark/pull/30206
