### ISSUE TITLE
spark 3.2.1 with hadoop 3.3 line

### ISSUE THREAD

**Issue by razvan** [stackabletech/spark-k8s-operator#66]
**Which new version of Apache Spark-on-Kubernetes should we support?**

spark 3.2.1 with hadoop 3.3 line

**Additional information**

Currently only hadoop 3.2 is supported

**Changes required**

Are there any upstream changes that we need to support?
e.g. new features, changed features, deprecated features etc.

**Implementation checklist**

Please don't change anything in this list.
Not all of these steps are necessary for all versions.

- [ ] Update the Docker image
- [ ] Update documentation to include supported version(s)
- [ ] Update operator to support the new version (if needed)
- [ ] Update integration tests to test use the new versions (in addition or replacing old versions
- [ ] Update examples to use new versions

**Comment by lfrancke** [comment]
One good reason to upgrade to Hadoop 3.3 is a vastly improved S3A Connector that comes with it.

**Comment by razvan** [comment]
Done (but the integration issue is still open)
