### ISSUE TITLE
Make spark-home configurable

### ISSUE THREAD

**Issue by adwk67** [stackabletech/spark-k8s-operator#68]
As a user I want to be able to configure the location of the spark home directory, so that I can build custom/job-specific images.

Currently the operator assumes that the spark-submit script is located in `/stackable/spark/bin` (which is therefore a limitation that must be considered when building docker images). This issue will relax this requirement and will cover:

- keep the above location as a default value (to be used with stackable images)
- add an extra Resource field to let this be overwritten

**Comment by razvan** [comment]
I propose to close this issue and only implement if there is a real need for it. Currently I don't see it.

**Comment by razvan** [comment]
As discussed with @adwk67

**Comment by adwk67** [comment]
Re-opening this as there *does* appear to be a need for it.
From an internal discussion:

> Installing dependencies at runtime for Spark jobs has a problem with the fact that the stackable user’s home directory doesn’t exist. Either we should change the home directory for the user to a location that exists or create /home/stackable:
│ :: loading settings :: url = jar:file:/stackable/spark-3.4.0-bin-hadoop3/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml                                                                                                  
│ Ivy Default Cache set to: /home/stackable/.ivy2/cache                                                                                                                                                                                      │
│ The jars for the packages stored in: /home/stackable/.ivy2/jars                                                                                                                                                                            
│ org.apache.iceberg#iceberg-spark-runtime-3.4_2.12 added as a dependency                                                                                                                                                                    │
│ :: resolving dependencies :: org.apache.spark#spark-submit-parent-aac99a1a-825d-4049-8607-4770d7e8c379;1.0                                                                                                                                 
│     confs: [default]
│ Exception in thread "main" java.io.FileNotFoundException: /home/stackable/.ivy2/cache/resolved-org.apache.spark-spark-submit-parent-aac99a1a-825d-4049-8607-4770d7e8c379-1.0.xml (No such file or directory)

**Comment by adwk67** [comment]
Closing this again as this issue was to do with making spark-home *configurable*, rather than setting it.
