### ISSUE TITLE
Add imagePullPolicy to SparkApplication CRD

### ISSUE THREAD

**Issue by adwk67** [stackabletech/spark-k8s-operator#69]
As a user I want to be able to configure the pull-policy for `SparkApplication` job images, so that custom/job-specific images can be re-built and - if required - automatically reloaded into the Kubernetes cluster.

This issue will cover:

- add and handle an optional field imagePullPolicy to the SparkApplication CRD

**Comment by lfrancke** [comment]
This might be relevant but Andrew tells me it's probably not: https://github.com/stackabletech/issues/issues/141
