### ISSUE TITLE
Monitor spark jobs at a granular level using delight: https://github.com/datamechanics/delight

### ISSUE THREAD

**Issue by adwk67** [stackabletech/spark-k8s-operator#7]
As a user of Spark-on-k8s I want to monitor spark jobs at a granular level using [delight](https://github.com/datamechanics/delight). See [also](https://www.datamechanics.co/delight).

This story is complete when: 
- it has been documented how spark-in-kubernetes mode treats logging and monitoring (in the light of the fact that the executor pods are terminated once they have completed).
- it has been shown that (and documented how) delight can be used in a spark/k8s context

**Comment by fhennig** [comment]
Here are the instructions on how to integrate it with the google spark-k8s operator: https://github.com/datamechanics/delight/blob/main/documentation/spark_operator.md

From the looks of it, it is very easy to add:
- Add their jar to the dependencies
- set 2 config options for spark

and you're done!

**Comment by soenkeliebau** [comment]
Can we maybe auto generate the token if the user doesn't specify it?

**Comment by fhennig** [comment]
Hey @adwk67 , I think we can close this for now, we won't do any delight integration currently if I'm not mistaken

**Comment by adwk67** [comment]
Yes, I agree. Will close it.
